apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-service-staging

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

images:
  - name: 123456789.dkr.ecr.ap-south-1.amazonaws.com/user-service
    newTag: STAGING_TAG    # replaced by Jenkins at deploy time
